pipeline {
    agent any

    environment {
        // Replace with your GitHub repo credentials ID
        GITHUB_CREDENTIALS = 'github-creds'
        VENV_DIR = '.venv'
    }
   stages {
        stage('Install dependencies') {
            steps {
                sh 'pip3 install -r requirements.txt'
            }
        }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/EgehizaJoy/alx-backend-python.git',
                    credentialsId: "${GITHUB_CREDENTIALS}"
            }
        }

        stage('Set up Python Environment') {
            steps {
                sh '''
                    python3 -m venv ${VENV_DIR}
                    . ${VENV_DIR}/bin/activate
                    pip install --upgrade pip
                    pip install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    . ${VENV_DIR}/bin/activate
                    pytest messaging_app/tests/ --junitxml=report.xml
                '''
            }
            post {
                always {
                    junit 'report.xml'
                }
            }
        }
    }
}
