apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-blue  # Change to django-green when switching
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
